supress logs off no blocks when no nonce found
allora-network/allora-offchain-node pull request #52
Opened 2024-09-05 10:33 UTC by okedeji

## Purpose of Changes and their Description

## Link(s) to Ticket(s) or Issue(s) resolved by this PR

## Are these changes tested and documented?

- [ ] If tested, please describe how. If not, why tests are not needed.
- [ ] If documented, please describe where. If not, describe why docs are not needed.
- [ ] Added to `Unreleased` section of `CHANGELOG.md`?

## Still Left Todo

*Fill this out if this is a Draft PR so others can help.*

2024-09-05 10:44 UTC, xmariachi requested changes

2024-09-05 10:44 UTC, xmariachi commented on usecase/spawn_actor_processes.go
>  			log.Debug().Uint64("topicId", worker.TopicId).Int64("BlockHeight", latestOpenWorkerNonce.BlockHeight).Msg("Got latest open worker nonce")
the problem is in this line, the else is always printing that line and is misleading.
Suggestion: 
* remove this else (line 65)
* remove the new lines (68-73)
* add an else in line 82, and add this message: 

```
log.Debug().Uint64("topicId", worker.TopicId).Msg("No new worker nonce found")
```
this will not give away extra misleading information

2024-09-05 10:46 UTC, okedeji commented on usecase/spawn_actor_processes.go
>  			log.Debug().Uint64("topicId", worker.TopicId).Int64("BlockHeight", latestOpenWorkerNonce.BlockHeight).Msg("Got latest open worker nonce")
haha yeah I fixed before you comment, can you reload and check again?

2024-09-05 17:55 UTC, kpeluso commented on usecase/spawn_actor_processes.go
> +			continue
technically could just keep the first log line and remove the other 2. This will still skip the misleading log in the `else` block below

2024-09-19 17:18 UTC, xmariachi commented
This has been tackled in [another PR](https://github.com/allora-network/allora-offchain-node/pull/56).

2024-09-19 17:18 UTC, closed without merging